steps: 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/microservices-261108/microservices-python','.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/microservices-261108/microservices-python']
     
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta','run','deploy','python-image','--image','gcr.io/microservices-261108/microservices-python','--region','us-central1', '--platform','managed','--allow-unauthenticated']
 
images:
- gcr.io/microservices-261108/microservices-python
