apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronpython
              image: shubhadag123/host-details-logic
              command: ["echo",  "Hello world"]
          restartPolicy: OnFailure