steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/microservices-261108/angular-docker', 'Microservices_Angular/.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/microservices-261108/angular-docker']

  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'python-docker', '--image', 'gcr.io/microservices-261108/angular-docker', '--region', 'us-east1', '--platform', 'managed',--allow-unauthenticated]

